version: '2'
services:
  myrepo:
    build: ../myrepo
    ports:
      - "9010:9010"
    command: ./entrypoint
    # volumes:
    #  - $REPO_BASE/warriortrading.hermes.demo-backend /src/app
volumes:
  redis:
    driver: local
  dir:
    driver: local
