version: '2'
services:
  myrepo:
    container_name: myrepo
    image: myrepo
    links:
      - "redis:redis"
    ports: 
      - "80:80"
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - "redis:/data"
volumes:
  redis:
    driver: local
