version: '2'
services:
  myrepo:
    build: ../myrepo
    ports:
      - "9010:9010"
    command: ./entrypoint
    volumes:
     - /var/lib/jenkins/workspace/testpip/myrepo/mochawesome-report:/src/app/mochawesome-report
volumes:
  mydir:
    external:
     name: mydir
