version: '2'
services:
  myrepo:
    build: ../myrepo
    ports:
      - "9010:9010"
    command: ./entrypoint
     volumes:
      - .:/mochawesome-report
volumes:
  redis:
    driver: local
  dir:
    driver: local
