version: '2'
services:
  myrepo:
    build: ../myrepo
    ports:
      - "9010:9010"
    command: ./entrypoint
    volumes:
     - /var/lib/jenkins/workspace/testpip/myrepo:/var/dir
volumes:
  mydir:
    driver: local
